// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lewlpitdcjfckigputqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxld2xwaXRkY2pmY2tpZ3B1dHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjU1ODksImV4cCI6MjA2NjI0MTU4OX0.vdIbW5cboEIpMwemjanWSEjPCuvSJ33JnSHV_n11rz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);